Update sphinx version
This commit updates sphinx version which aligns to g-r. Without this
patch, py27 tests fail because of an error like this:

 ERROR: Sphinx requires Python '>=3.5' but the running Python is 2.7.15

Change-Id: Iaaf4b2dabd04f85217cb4a1af9af79165e5b1ba9