Change test order to avoid incompatibliity
If py26 or py27 tests are run first, there is a incompatibility in
the .testrepository that breaks several tests.  To get around this,
you need to run the py33 tests first.  This change was made over in
the cliff project.

Before:
    (.venv)terry@brat:~/bashate$ rm -rf .testrepository/
    (.venv)terry@brat:~/bashate$ tox
      ...
      py26: commands succeeded
      py27: commands succeeded
    ERROR:   py33: commands failed
    ERROR:   py34: commands failed
    ERROR:   pypy: commands failed
      pep8: commands succeeded
After:
    (.venv)terry@brat:~/bashate$ rm -rf .testrepository/
    (.venv)terry@brat:~/bashate$ tox
      ...
      py33: commands succeeded
      py34: commands succeeded
      py26: commands succeeded
      py27: commands succeeded
      pypy: commands succeeded
      pep8: commands succeeded
      congratulations :)
    (.venv)terry@brat:~/bashate$

Change-Id: I837eecd55e51c3ff10f8e9429f5eca94a2e58b38